#!/usr/bin/perl

use strict;
use TinderboxDS;
use Getopt::Std;

my $opts = {};

getopts('n:t:', $opts);

if (!$opts->{'n'} || !$opts->{'t'}) {
        die "usage: $0 -n <jail name> -t <CVS tag>\n";
}

my $name = $opts->{'n'};
my $tag  = $opts->{'t'};

my $ds = new TinderboxDS();

if ($ds->isValidJail($name)) {
        die "ERROR: A jail named $name is already in the datastore.\n"
}

my $jail = new Jail({Name => $name, Tag => $tag});

my $rc = $ds->addJail($jail);

if (!$rc) {
        die "ERROR: Failed to add jail $jail to the datastore: "
            . $ds->getError() . ".\n";
}

$ds->destroy();
exit(0);
