#!/bin/sh

usage () {
    echo "usage: $0 -n <jail name> -t <jail tag> [-d <description>] [-u <update command|CVSUP|NONE>]"
    exit 1
}

if [ `id -u` != 0 ]; then
    echo "ERROR: You must be root to run $0."
    exit 1
fi

pb=/space
suphost=cvsup12.FreeBSD.org
cvsup_compress= #*default compress

jail_name=""
jail_tag=""
descr=""
update_cmd=""

while [ $# -gt 0 ]; do
    case "x$1" in
	x-n)
	  jail_name="$2"; shift;
	  ;;
	x-t)
	  jail_tag="$2"; shift;
	  ;;
	x-d)
	  descr="$2"; shift;
	  ;;
	x-u)
	  update_cmd="$2"; shift;
	  ;;
	*)
	  usage
	  ;;
    esac
    shift
done

if [ -z "${jail_name}" -o -z "${jail_tag}" ]; then
    usage
fi

_jails=$(${pb}/scripts/tc listJails)
if echo ${_jails} | grep -qw ${jail_name}; then
    echo "ERROR: Jail, \"${jail_name}\" already exists."
    exit 1
fi

echo -n "INFO: Creating directories and supfile for new jail..."
rm -rf ${pb}/jails/${jail_name}

mkdir -p ${pb}/jails/${jail_name}/src

cat > ${pb}/jails/${jail_name}/src-supfile << EOSF
*default host=${suphost}
*default base=${pb}/jails/${jail_name}
*default prefix=${pb}/jails/${jail_name}
*default release=cvs tag=${jail_tag}
*default delete use-rel-suffix
${cvsup_compress}
src-all
EOSF

echo "DONE."

# Add the new jail to the datastore.
echo -n "INFO: Adding jail to datastore..."
if [ ! -z "${descr}" ]; then
    descr="-d ${descr}"
fi
if [ ! -z "${update_cmd}" ]; then
    update_cmd="-u ${update_cmd}"
fi
${pb}/scripts/tc addJail -n ${jail_name} -t ${jail_tag} ${update_cmd} "${descr}"

if [ $? != 0 ]; then
    echo "FAILED."
    exit 1
fi

echo "DONE."

echo "INFO: Initializing new jail..."
${pb}/scripts/mkjail ${jail_name}

if [ $? != 0 ]; then
    echo "FAILED."
    exit 1
fi

echo "DONE."

exit 0
