#!/bin/sh
#-
# Copyright (c) 2004-2005 FreeBSD GNOME Team <freebsd-gnome@FreeBSD.org>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#
# $Id: mkbuild,v 1.6 2005/02/13 07:08:33 marcus Exp $
#


pb=/space

_builds=$(${pb}/scripts/tc listBuilds)

if [ -z "$1" ]; then
    echo "Please specify a build name."
    echo "Current build names are:"
    for i in ${_builds}; do
	echo "	${i}"
    done
    exit 1
fi

build=$1
found=0

for _build in ${_builds}; do
    if [ "${_build}" = "${build}" ]; then
	found=1
	break
    fi
done
if [ ${found} = 0 ]; then
    echo "ERROR: Unknown build, \"${build}\"."
    exit 1
fi

jail=$(${pb}/scripts/tc getJailForBuild -b ${build})

if [ ! -f ${pb}/jails/${jail}/${jail}.tar ]; then
    echo "ERROR: Tarball for jail, ${jail}, does not exist."
    echo "ERROR: Run mkjail first."
    exit 1
fi

D=${pb}/${build}

umount -f ${D}/a/ports >/dev/null 2>&1
umount -f ${D}/usr/src >/dev/null 2>&1
umount -f ${D}/dev >/dev/null 2>&1
umount -f ${D}/distcache >/dev/null 2>&1
chflags -R noschg ${D}
rm -rf ${D}
mkdir -p ${D}

tar -C ${D} -xf ${pb}/jails/${jail}/${jail}.tar
