#!/bin/sh

pb=/space

_builds=$(${pb}/scripts/tc listBuilds)

if [ -z "$1" ]; then
    echo "Please specify a build name."
    echo "Current build names are:"
    for i in ${_builds}; do
	echo "	${i}"
    done
    exit 1
fi

build=$1

if ! echo ${_builds} | grep -qw ${build}; then
    echo "ERROR: Unknown build, \"${build}\"."
    exit 1
fi

jail=$(${pb}/scripts/tc getJailForBuild -b ${build})

if [ ! -f ${pb}/jails/${jail}/${jail}.tar ]; then
    echo "ERROR: Tarball for jail, ${jail}, does not exist."
    echo "ERROR: Run mkjail first."
    exit 1
fi

D=${pb}/${build}

chflags -R noschg ${D}
umount -f ${D}/a/ports >/dev/null 2>&1
umount -f ${D}/usr/src >/dev/null 2>&1
umount -f ${D}/dev >/dev/null 2>&1
rm -rf ${D}
mkdir -p ${D}

tar -C ${D} -xf ${pb}/jails/${jail}/${jail}.tar
