#!/bin/sh

pb=/space

_jails=$(${pb}/scripts/tc listJails)

if [ -z "$1" ]; then
    echo "Please specify a jail name."
    echo "Current jails are:"
    for i in ${_jails}; do
	echo "	${i}"
    done
    exit 1
fi

. ${pb}/scripts/buildenv

jail=$1

if ! echo ${_jails} | grep -qw ${jail}; then
    echo "ERROR: Unknown jail, \"${jail}\"."
    exit 1
fi

# We only care about SRCBASE, so the other parameters can be anything.
buildenv ${pb} "NULL" ${jail} "NULL"

update_cmd=$(${pb}/scripts/tc getSrcUpdateCmd -j ${jail})
if [ ! -z "${update_cmd}" ]; then
    eval ${update_cmd} > /dev/null 2>&1
fi

D=${pb}/jails/${jail}/tmp
chflags -R noschg ${D}
rm -rf ${D}

export __MAKE_CONF=${pb}/jails/${jail}/make.conf

cd ${SRCBASE}
mkdir -p ${D}
make world DESTDIR=${D}
cd etc
make distribution DESTDIR=${D}

cd ${D}
ln -sf dev/null kernel
ln -sf aj ${D}/etc/malloc.conf

touch -f ${D}/etc/fstab
touch -f ${D}/etc/wall_cmos_clock
echo "portmap_enable=\"NO\"" > ${D}/etc/rc.conf
echo "network_interfaces=\"\"" >> ${D}/etc/rc.conf
cp ${D}/usr/share/zoneinfo/EST5EDT ${D}/etc/localtime
chmod 0444 ${D}/etc/localtime
echo "domain marcuscom.com" > ${D}/etc/resolv.conf
echo "nameserver 192.168.1.1" >> ${D}/etc/resolv.conf

mtree -deU -f ${SRCBASE}/etc/mtree/BSD.root.dist -p ${D}/
mtree -deU -f ${SRCBASE}/etc/mtree/BSD.var.dist -p ${D}/var
mtree -deU -f ${SRCBASE}/etc/mtree/BSD.usr.dist -p ${D}/usr
mtree -deU -f ${SRCBASE}/etc/mtree/BSD.local.dist -p ${D}/usr/local

date '+%Y%m%d' > ${D}/var/db/port.mkversion
mkdir -p ${D}/var/run

rm -f ${D}/usr/lib/aout/lib*_p.a

cd ${D}
tar cf ${pb}/jails/${jail}/${jail}.tar.new .
mv -f ${pb}/jails/${jail}/${jail}.tar.new ${pb}/jails/${jail}/${jail}.tar

rm -rf ${D} 2> /dev/null
if [ -d ${D} ]; then
    chflags -R noschg ${D}
    rm -rf ${D}
fi
