#!/bin/sh -T

pb=$0
[ -z "$(echo "${pb}" | sed 's![^/]!!g')" ] && \
pb=$(type "$pb" | sed 's/^.* //g')
pb=$(realpath $(dirname $pb))
pb=${pb%%/scripts}

. ${pb}/scripts/tinderbox_shlib.sh

TINDERBUILD_ARGS="$*"
TINDERD_SLEEPTIME=$(parse_rawenv -t raw -a TINDERD_SLEEPTIME -q)
TINDERD_SLEEPTIME=${TINDERD_SLEEPTIME:=120}

main_loop() {
	while true ; do
    		trap "" 1
		ENTRY=$(${pb}/scripts/tc listBuildPortsQueue -s ENQUEUED -r 2>/dev/null | head -1)
		ID=$(echo ${ENTRY} | cut -d: -f1)
		USER=$(echo ${ENTRY} | cut -d: -f2)
		BUILD=$(echo ${ENTRY} | cut -d: -f3)
		PORT=$(echo ${ENTRY} | cut -d: -f4)
		MAIL=$(echo ${ENTRY} | cut -d: -f5)

		if [ -n "${BUILD}" -a -n "${PORT}" -a -n "${ID}" ] ; then
			echo "Going to build ${PORT} on ${BUILD}"
			${pb}/scripts/tc updateBuildPortsQueueEntryStatus -i "${ID}" -s PROCESSING
			${pb}/scripts/tc addPort -b "${BUILD}" -d "${PORT}" -r
			if ${pb}/scripts/tinderbuild -b "${BUILD}" ${TINDERBUILD_ARGS} "${PORT}" >/dev/null ; then
				${pb}/scripts/tc updateBuildPortsQueueEntryStatus -i "${ID}" -s SUCCESS
			else
				${pb}/scripts/tc updateBuildPortsQueueEntryStatus -i "${ID}" -s FAIL
			fi
			${pb}/scripts/tc updateBuildPortsQueueEntryCompletionDate -i "${ID}"
			if [ "${MAIL}" = "1" ] ; then
				${pb}/scripts/tc sendBuildCompletionMail -b "${BUILD}" -u ${USER}"
			fi
				
			${pb}/scripts/tc reorgBuildPortsQueue
		else
			echo "INFO: Nothing to do. Sleeping ${TINDERD_SLEEPTIME} seconds."
			trap main_loop 1
			sleep ${TINDERD_SLEEPTIME}
		fi
	done
}

main_loop
