<?php

define( 'preparing_next_build', 'preparing next build...' );

define( 'permission_denied', 'permission denied!' );

define( 'mandatory_input_fields_are_empty', 'Please make sure that all input fields are filled' );


define( 'user_admin_user_exists', 'User already exists!' );
define( 'user_admin_user_not_exist', 'User does not exist!' );
define( 'user_admin_user_name_changed', 'You are allowed to change your username!' );
define( 'user_admin_user_name_empty', 'You have to fill in a username!' );

define( 'user_login_not_enabled', 'User not enabled for WWW' );
define( 'user_login_wrong_data', 'username or password mismatch' );

?>
