<?php

define( 'preparing_next_build', 'preparing next build...' );

define( 'permission_denied', 'permission denied!' );

define( 'mandatory_input_fields_are_empty', 'Please make sure that all input fields are filled' );


define( 'user_admin_user_exists', 'User already exists!' );
define( 'user_admin_user_not_exist', 'User does not exist!' );
define( 'user_admin_user_name_changed', 'You are allowed to change your username!' );
define( 'user_admin_user_name_empty', 'You have to fill in a username!' );

define( 'user_login_not_enabled', 'User not enabled for WWW' );
define( 'user_login_wrong_data', 'username or password mismatch' );

define( 'build_ports_queue_priority_to_low', 'The Priority you have chosen is toolow' );
define( 'build_ports_queue_not_allowed_to_add', 'You are not allowed to add these Build Ports Queue Entry (check permissions for build)' );
define( 'build_ports_queue_not_allowed_to_delete', 'You are not allowed to delete the selected Build Ports Queue Entry' );
define( 'build_ports_queue_not_allowed_to_modify', 'You are not allowed to modify the selected Build Ports Queue Entry (check permissions for build)' );

?>
