#!/bin/sh

dir=$1
phase=$2

if [ $phase = 1 ]; then

    cd $dir || exit 1
    echo "maintained by: $(make maintainer)"
    echo "build started at $(date)"

    cd /tmp/depends
    export PKG_PATH=/tmp/depends
    if [ "$(echo $(/bin/ls | wc -c))" != 0 ]; then
	echo "adding dependencies"
	for i in *.t[bg]z; do
	    echo "pkg_add $i"
	    base=$(basename $i .tgz)
	    base=$(basename $base .tbz)
	    if pkg_info -q -e $base; then
		echo "skipping $base, already added"
	    else
	        if ! pkg_add $i; then
		    echo "error in dependency $i, exiting"
		    echo "1" > /tmp/status
		    exit 1
		fi
	    fi
	done
    fi

    cd $dir || exit 1
    pkgname=$(make package-name)
    echo "================================================================"
    echo "====================<phase 1: make checksum>===================="

    if /pnohang $TIMEOUT /tmp/make.log1 ${pkgname} make checksum; then
	cat /tmp/make.log1
echo "0" > /tmp/status
    else
	cat /tmp/make.log1
	echo "1" > /tmp/status
	echo "================================================================"
	echo -n "build ended at "
	date
    fi
else

    xvfb=0
    if which -s Xvfb; then
	xvfb=1
	pid=$(echo $$ % 32768 | bc)
	X11BASE=$(which Xvfb | sed -e 's./bin/Xvfb..')
	Xvfb :${pid} -fp ${X11BASE}/lib/X11/fonts/misc &
	DISPLAY=:${pid}
	export DISPLAY
    fi

    echo "====================<phase 2: make package>====================="
    cat > /tmp/mtree.exclude <<EOF
./root/*
./var/*
./tmp/*
./etc/make.conf.bak
./etc/make.conf
EOF
    mtree -X /tmp/mtree.exclude -xcn -k uid,gid,mode -p / > /tmp/mtree
    cd $dir || exit 1
    pkgname=$(make package-name)
    if /pnohang $TIMEOUT /tmp/make.log2 ${pkgname} make package; then
	cat /tmp/make.log2
	echo "0" > /tmp/status
	prefix=$(make -V PREFIX)
	echo "================================================================"
	echo "checking installed files"
	find ${prefix} \( \( -perm -4000 -o -perm -2000 -a \! -type d \) -o \( -perm -0002 -o -perm -0020 \) \) -a \! -type l -ls | sort > /tmp/list1
	echo "pkg_delete -f ${pkgname}"
	pkg_delete -f ${pkgname}
	find ${prefix} \( \( -perm -4000 -o -perm -2000 -a \! -type d \) -o \( -perm -0002 -o -perm -0020 \) \) -a \! -type l -ls | sort > /tmp/list2
	if ! diff -qb /tmp/list1 /tmp/list2 2>/dev/null; then
	    echo "================================================================"
	    echo "found set[ug]id or world-writable files and directories"
	    diff -b /tmp/list2 /tmp/list1 | grep '^>'
	fi

	mtree -X /tmp/mtree.exclude -x -f /tmp/mtree -p / | egrep -v '^(usr/local/var|usr/local/www/|usr/X11R6/lib/X11/xserver/SecurityPolicy|usr/local/share/nls/POSIX|usr/local/share/nls/en_US.US-ASCII|etc/shells.bak|etc/services|compat |usr/X11R6 |etc/manpath.config|usr/local/info/dir)' > /tmp/list3

	if [ -s /tmp/list3 ]; then
	    cd /
	    grep ' extra$' /tmp/list3 | awk '{print $1}' | xargs -J % find % -ls > /tmp/list4
	    grep ' missing$' /tmp/list3 > /tmp/list5
	    grep -vE ' (extra|missing)$' /tmp/list3 > /tmp/list6
	    if [ "x${PLISTCHECK}" != "x" ]; then
		if grep -qE 'usr/(local|X11R6)/(bin/|include/|man/|sbin/|share/|share/|lib/|libdata/|libexec/)' /tmp/list4; then
		    echo "1" > /tmp/status
		fi
		if [ -s /tmp/list5 ]; then
		    echo "1" > /tmp/status
		fi
	    fi
	    echo "================================================================"
	fi

	cd /var/db/pkg
	if [ $(echo $(echo * | wc -c)) != 2 ]; then
	    echo "deleting dependencies"
	    prevlist=""
	    count=1
	    while [ $(echo $(echo * | wc -c)) != 2 -a $(echo $(echo * | wc -c)) != $(echo $(echo $prevlist | wc -c)) ]; do
		echo "== phase $count =="
		prevlist="$(echo *)"
		for i in *; do
		    echo "pkg_delete -rf ${i}"
		    pkg_delete -rf ${i}
		done
		count=$(($count + 1))
	    done
	fi

	echo
	echo "=== Checking filesystem state"

	if [ -s /tmp/list4 ]; then
	    echo "list of extra files and directories in / (not present before this port was installed but present after it was deinstalled)"
	    cat /tmp/list4
	fi
	if [ -s /tmp/list5 ]; then
	    echo "list of files present before this port was installed but missing after it was deinstalled"
	    cat /tmp/list5
	fi
	if [ -s /tmp/list6 ]; then
	    echo "list of filesystem changes from before and after port installation and deinstallation"
	    cat /tmp/list6
	    if [ "x${PLISTCHECK}" != "x" ]; then
		echo "1" > /tmp/status
	    fi
	fi

	if grep -q PORT_TRIES_TO_WRITE_TO_HOME /tmp/make.log2; then
	    echo "1" > /tmp/status
	fi
    else
	cat /tmp/make.log2
	echo "1" > /tmp/status
    fi

    if [ ${xvfb} = 1 ]; then
	kill $(jobid %1)
    fi

    if [ -e ${dir}/.keep ]; then
	cd ${dir}
	objdir=$(make -V WRKDIR)
	tar cfjC /tmp/work.tbz ${objdir}/.. work
    fi

    echo "================================================================"
    echo -n "build ended at "
    date
fi

exit 0
