.\" Copyright (c) 2005 FreeBSD GNOME Team <freebsd-gnome@FreeBSD.org>
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
.\" OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
.\" IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
.\" INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
.\" NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
.\" DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
.\" THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
.\" THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\"
.\" $MCom: portstools/tinderbox/man/man1/tc-init.1,v 1.1 2005/07/27 03:59:49 marcus Exp $
.\"
.Dd July 21, 2005
.Os FreeBSD
.Dt TC-INIT 1
.Sh NAME
.Nm "tc init"
.Nd Initialize a tinderbox environment
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Nm
will perform the necessary steps to initialize the
.Pa Tinderbox
environment.  In particular, it will create the various directories
.Pa Tinderbox
will use.
.Nm
should only be run once before using
.Pa Tinderbox .
It takes no arguments.
.Sh EXAMPLES
.Cm ${pb}/scripts/tc
.Cm init
.Pp
Where
.Cm ${pb}
is your Tinderbox (or port build) root directory.
.Sh LICENSE AND DISCLAIMER
BSD License
