#!/bin/sh
#
# Copyright (c) 2008 Ade Lovett <ade@FreeBSD.org>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#
# $MCom: portstools/tinderbox/sql/genschema,v 1.4 2012/06/20 20:47:42 ade Exp $
#
# Create a full-blown schema from a series of files, reducing duplication
#
# Usage:	genschema mysql|pgsql

#---------------------------------------------------------------------------
# Argument handling
#
if [ $# -ne 1 ]; then
    echo "usage: genschema mysql|pgsql|sqlite"
    exit 1
fi

case $1 in
"mysql"|"pgsql"|"sqlite")	dbtype=$1;;
*)				echo "genschema: unknown database type: $1"
				exit 1;;
esac

#---------------------------------------------------------------------------
# Kick out the generated schema
#
cat schema.${dbtype}.pre \
    values.config values.hooks values.lp values.pfr \
    values.pfp schema.${dbtype}.post
exit 0
